### ISSUE TITLE
Might want to update your nmp page instructions

### ISSUE THREAD

**Issue by kenlnetherland** [andreas-marschke/grunt-scram#2]

**Comment by andreas-marschke** [comment]
Would you be able to elaborate?
 
This repository has been lying around for a very long time if you take a look. The code is very simple, if you're interested in contributing. 

I don't even think the larger community still uses grunt as their tool chain.

**Comment by kenlnetherland** [comment]
Your npm instructions are different from your Github instructions.  If I
remember correctly, the config section.

I use Grunt exclusively, are you aware of better or more common tool sets
these days?

Thanks,

Ken

**Comment by andreas-marschke** [comment]
> Your npm instructions are different from your Github instructions.  If I remember correctly, the config section.

Please present those differences here or submit a merge request. A roundabout description does not merit a change. Nor did the initial ticket. Please respect maintainers by learning how to write bug reports:  https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

> I use Grunt exclusively, are you aware of better or more common tool sets these days?

Large swaths of the community have moved on to tools like webpack, use npm scripts as they've become more useful or have integrations through their frontend toolsets.
